version: '3.7'

volumes:
  acme: {}

services:
  traefik:
    command: --certificatesResolvers.letsencrypt.acme.email=${traefik_email}
    volumes:
      - ./.docker/traefik/traefik.prod.yml:/etc/traefik/traefik.yml:ro
      - acme:/var/lib/traefik
    labels:
      - traefik.http.middlewares.traefik_auth.basicauth.users=${traefik_auth}
      - ghosts.auth=true

  ghosts:
    command: -nohosts -proxymode -webnavbgcolor "#ffffff" -webnavtextcolor "#50596c"
    labels:
      - traefik.http.middlewares.traefik_auth.basicauth.users=${ghosts_auth}

  adminer:
    labels:
      - traefik.http.middlewares.adminer_auth.basicauth.users=${adminer_auth}
      - ghosts.auth=true