version: '3.7'

networks:
  server_proxy:
    name: server_proxy
  server_db:
    name: server_db

services:
  traefik:
    image: traefik:v2.7
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - server_proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik_secure.entrypoints=websecure
      - traefik.http.routers.traefik_secure.rule=Host(`${traefik_url}`)
      - traefik.http.routers.traefik_secure.tls=true
      - traefik.http.routers.traefik_secure.service=api@internal

      - ghosts.host=${traefik_url}
      - ghosts.category=~Toolkit
      - ghosts.logo=static/logos/traefik.png
      - ghosts.description=Traefik is a modern HTTP reverse proxy and load balancer that makes deploying microservices easy.
      - ghosts.proto=https

  ghosts:
    image: lobre/ghosts
    container_name: ghosts
    restart: unless-stopped
    networks:
      - server_proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./logos/:/app/static/logos/
    depends_on: 
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.ghosts_secure.entrypoints=websecure
      - traefik.http.routers.ghosts_secure.rule=Host(`${ghosts_url}`)
      - traefik.http.routers.ghosts_secure.tls=true

      - ghosts.host=${ghosts_url}
      - ghosts.noweb=true
      - ghosts.proto=https

  adminer:
    image: adminer:4.8.1-standalone
    container_name: adminer
    restart: unless-stopped
    networks:
      - server_proxy
      - server_db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./.docker/adminer/plugins-enabled/:/var/www/html/plugin-enabled/:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.adminer_secure.entrypoints=websecure
      - traefik.http.routers.adminer_secure.rule=Host(`${adminer_url}`)
      - traefik.http.routers.adminer_secure.tls=true

      - ghosts.host=${adminer_url}
      - ghosts.category=~Toolkit
      - ghosts.logo=static/logos/adminer.png
      - ghosts.description=Adminer is a full-featured database management tool written in PHP.
      - ghosts.proto=https
    