log:
  level: DEBUG

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json

api:
  dashboard: true

entryPoints:
  web:
    address: :80
    http:
      middlewares:
        - security
      redirections:
        entryPoint:
          to: websecure


  websecure:
    address: :443
    http:
      middlewares:
        - security
      tls:
        certResolver: letsencrypt

tls:
  options:
    default:
      minVersion: VersionTLS12

http:
  middlewares:
    security:
      headers:
        customResponseHeaders:
          x-powered-by: "" # Hide PHP version for example

providers:
  docker:
    exposedByDefault: false
    network: "server_proxy"
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      storage: "/var/lib/traefik/acme.json"
      tlsChallenge: {}