log:
  level: DEBUG

api:
  dashboard: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure


  websecure:
    address: :443
    http:
      tls:
        certResolver: letsencrypt

providers:
  docker:
    exposedByDefault: false
    network: "server_proxy"
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      storage: "/var/lib/traefik/acme.json"
      httpChallenge:
        entryPoint: web