log:
  level: DEBUG

accessLog: {}

api:
  dashboard: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: :443

providers:
  docker:
    exposedByDefault: false
    network: "server_proxy"
    watch: true

  file:
    filename: "/etc/traefik/certificates.yml"
    watch: true